# Generated by Django 6.0.1 on 2026-02-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время начала отправки")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_moderation", "На модерации"),
                            ("created", "Создана"),
                            ("started", "Готова к отправке"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="on_moderation",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("is_moderated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_moderated_mailing", "Can moderated mailing"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Успешно"), ("failed", "Ошибка")],
                        max_length=20,
                        verbose_name="Статус отправки",
                    ),
                ),
                ("is_sending", models.BooleanField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True, verbose_name="Детали отправки")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Попытка отправки рассылки",
                "verbose_name_plural": "Попытки отправки рассылок",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme_mail", models.CharField(blank=True, max_length=50, null=True, verbose_name="Тема письма")),
                ("text_mail", models.TextField(verbose_name="Текст письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "permissions": [("can_view_message", "Can view message")],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("first_name", models.CharField(max_length=50, null=True, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, null=True, verbose_name="Фамилия")),
                ("middle_name", models.CharField(max_length=50, null=True, verbose_name="Отчество")),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Введите комментарий",
                        max_length=200,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "permissions": [("can_view_recipient", "Can view recipient")],
            },
        ),
    ]
