# Generated by Django 6.0.2 on 2026-02-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ сервера"),
        ),
    ]
